name: Notify Slack
on:
  release:
    types: [ created ]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: releaseBot
          SLACK_ICON: ""
          SLACK_ICON_EMOJI: ":floppy_disk:"
          SLACK_TITLE: "nDAX Release: ${{github.event.release.tag_name}} - ${{github.event.release.name}}"
          SLACK_MESSAGE: "${{github.event.release.body}}"
